name: ci

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Set up node modules
        run: npm ci
      - name: Execute tests
        run: npm test